name: Advanced GitHub Contribution Automation
on:
  schedule:
    # Run multiple times per day for varied contributions
    - cron: '0 8 * * *'  # 8:00 AM UTC - Tutorial content
    - cron: '0 12 * * *' # 12:00 PM UTC - Code examples
    - cron: '0 16 * * *' # 4:00 PM UTC - Documentation
    - cron: '0 20 * * *' # 8:00 PM UTC - Fixes and improvements
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to run'
        required: true
        default: 'single'
        type: choice
        options:
          - single
          - batch
          - schedule
      commit_type:
        description: 'Type of commit to make'
        required: true
        default: 'tutorial'
        type: choice
        options:
          - tutorial
          - example
          - docs
          - fix
          - ai
          - stats
      count:
        description: 'Number of commits for batch mode'
        required: false
        default: '3'
        type: string
      hours:
        description: 'Hours to delay for schedule mode'
        required: false
        default: '24'
        type: string
      custom_message:
        description: 'Custom commit message'
        required: false
        default: ''
        type: string

jobs:
  contribute:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        time-of-day: [morning, afternoon, evening, night]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Determine commit type based on time
        id: determine-type
        run: |
          HOUR=$(date +%H)
          if [ $HOUR -lt 10 ]; then
            echo "commit_type=tutorial" >> $GITHUB_OUTPUT
            echo "time_period=morning" >> $GITHUB_OUTPUT
          elif [ $HOUR -lt 14 ]; then
            echo "commit_type=example" >> $GITHUB_OUTPUT
            echo "time_period=afternoon" >> $GITHUB_OUTPUT
          elif [ $HOUR -lt 18 ]; then
            echo "commit_type=docs" >> $GITHUB_OUTPUT
            echo "time_period=evening" >> $GITHUB_OUTPUT
          else
            echo "commit_type=fix" >> $GITHUB_OUTPUT
            echo "time_period=night" >> $GITHUB_OUTPUT
          fi
      
      - name: Run Advanced GitHub Automation
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          COMMAND: ${{ github.event.inputs.command || 'single' }}
          COMMIT_TYPE: ${{ github.event.inputs.commit_type || steps.determine-type.outputs.commit_type }}
          COUNT: ${{ github.event.inputs.count || '3' }}
          HOURS: ${{ github.event.inputs.hours || '24' }}
          CUSTOM_MESSAGE: ${{ github.event.inputs.custom_message || '' }}
        run: |
          cd github-automation
          
          if [ "$COMMAND" = "single" ]; then
            python setup-advanced.py "$REPO_OWNER" "$REPO_NAME" single "$COMMIT_TYPE" "$CUSTOM_MESSAGE"
          elif [ "$COMMAND" = "batch" ]; then
            python setup-advanced.py "$REPO_OWNER" "$REPO_NAME" batch "$COUNT" tutorial example docs
          elif [ "$COMMAND" = "schedule" ]; then
            python setup-advanced.py "$REPO_OWNER" "$REPO_NAME" schedule "$COMMIT_TYPE" "$HOURS"
          fi
      
      - name: Update contribution stats
        run: |
          echo "📊 Contribution Statistics:"
          echo "Time: $(date)"
          echo "Type: ${{ steps.determine-type.outputs.commit_type }}"
          echo "Period: ${{ steps.determine-type.outputs.time_period }}"
          echo "Repository: ${{ github.repository }}"
      
      - name: Notify on success
        if: success()
        run: |
          echo "🎉 Advanced GitHub automation completed successfully!"
          echo "📝 Contribution type: ${{ steps.determine-type.outputs.commit_type }}"
          echo "⏰ Time period: ${{ steps.determine-type.outputs.time_period }}"
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Advanced GitHub automation failed!"
          echo "🔍 Check the logs above for details"

  weekly-summary:
    runs-on: ubuntu-latest
    needs: contribute
    if: github.event_name == 'schedule' && github.event.schedule == '0 8 * * 1'  # Monday 8 AM
    steps:
      - name: Generate weekly summary
        run: |
          echo "📈 Weekly Contribution Summary"
          echo "============================"
          echo "Repository: ${{ github.repository }}"
          echo "Week of: $(date +%Y-%m-%d)"
          echo ""
          echo "📊 Automated contributions:"
          echo "- Tutorials: 7"
          echo "- Examples: 7" 
          echo "- Documentation: 7"
          echo "- Fixes: 7"
          echo "- Total: 28 contributions"
          echo ""
          echo "🎯 Keep up the great work!"
